version: "2.0"
#rename to docker-compose

services:
    master: 
      image: elasticsearch:2.4
      environment: 
        ES_HEAP_SIZE: 512M
      mem_limit: 1g
      volumes:
        - /etc/localtime:/etc/localtime:ro
        #- /home/ozlevka/disk/data/devclustersnap:/usr/share/elasticsearch/snapshot
      networks:
        - devcluster
      ports: 
        - "9200:9200"
      command: "elasticsearch -Des.cluster.name=devcluster -Des.node.data=false -Des.node.master=true -Dpath.repo=/usr/share/elasticsearch/snapshot"
    elasticnode1:
      image: elasticsearch:2.4
      environment: 
        ES_HEAP_SIZE: 2g
      mem_limit: 3g
      volumes:
        #- /home/ozlevka/disk/data/devcluster:/usr/share/elasticsearch/data
        #- /home/ozlevka/disk/data/devclustersnap:/usr/share/elasticsearch/snapshot
        - /etc/localtime:/etc/localtime:ro
      links: 
        - master
      command: "elasticsearch -Des.cluster.name=devcluster -Des.node.data=true -Des.node.master=false -Ddiscovery.zen.ping.unicast.hosts=master -Dpath.repo=/usr/share/elasticsearch/snapshot"
      networks:
        - devcluster
    elasticnode2:
      image: elasticsearch:2.4
      environment: 
        ES_HEAP_SIZE: 2g
      mem_limit: 3g
      volumes:
        #- /home/ozlevka/disk/data/devcluster:/usr/share/elasticsearch/data
        #- /home/ozlevka/disk/data/devclustersnap:/usr/share/elasticsearch/snapshot
        - /etc/localtime:/etc/localtime:ro
      links: 
        - master
      command: "elasticsearch -Des.cluster.name=devcluster -Des.node.data=true -Des.node.master=false -Ddiscovery.zen.ping.unicast.hosts=master -Dpath.repo=/usr/share/elasticsearch/snapshot"
      networks:
        - devcluster
    kibana:
      image: ozlevka/kibana-sense:4.6
      command: kibana -e http://master:9200
      mem_limit: 512m
      volumes:
        - /etc/localtime:/etc/localtime:ro
      ports: 
        - "5601:5601"
      links:
        - master
      networks:
        - devcluster
networks:
  devcluster:
    driver: bridge